### ISSUE TITLE
Got Max retries exceeded with url: /kubernetes/kubernetes/release-1.14/api/openapi-spec/swagger.json 

### ISSUE THREAD

**Issue by irvifa** [kubernetes-client/gen#114]
I got the following error:

```
$ ${GEN_ROOT}/gen/openapi/java.sh kubernetes ./settings
--- Building docker image kubernetes-java-client-gen:v1...
Sending build context to Docker daemon  143.9kB
Step 1/26 : FROM maven:3.5-jdk-8-slim
 ---> a045f84d6a3d
Step 2/26 : ARG SWAGGER_CODEGEN_COMMIT
 ---> Using cache
 ---> c4c0a39c22ce
Step 3/26 : ARG GENERATION_XML_FILE
 ---> Using cache
 ---> ec19cbb39e86
Step 4/26 : ARG SWAGGER_CODEGEN_USER_ORG=swagger-api
 ---> Using cache
 ---> 4b6d772f4057
Step 5/26 : RUN apt-get update && apt-get -y install git python-pip && pip install urllib3
 ---> Using cache
 ---> a2a20cf3ba81
Step 6/26 : RUN apt-get update && apt-get -qq -y install libunwind8 libicu57 libssl1.0 liblttng-ust0 libcurl3 libuuid1 libkrb5-3 zlib1g
 ---> Using cache
 ---> 24be2cc95919
Step 7/26 : RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
 ---> Using cache
 ---> e59ac3b89f21
Step 8/26 : RUN apt-get update && apt-get -y install     nodejs     libunwind8-dev     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 1bc73d8794ea
Step 9/26 : RUN npm install -g autorest
 ---> Using cache
 ---> 06d3009eac02
Step 10/26 : RUN mkdir /source &&     cd /source &&     git clone -n https://github.com/${SWAGGER_CODEGEN_USER_ORG}/swagger-codegen.git &&     cd swagger-codegen &&     git checkout $SWAGGER_CODEGEN_COMMIT
 ---> Using cache
 ---> d477602a1ee6
Step 11/26 : RUN mkdir /.npm && chmod -R go+rwx /.npm && chmod -R go+rwx /root && umask 0 && cd /source/swagger-codegen &&     mvn install -DskipTests -Dmaven.test.skip=true -pl modules/swagger-codegen-maven-plugin -am &&     cp -r /root/.m2/* /usr/share/maven/ref
 ---> Using cache
 ---> 0f3181b9b0a8
Step 12/26 : RUN mkdir -p /node_modules && chmod -R go+rwx /node_modules
 ---> Using cache
 ---> 84acc5beb3b5
Step 13/26 : RUN npm install @microsoft.azure/autorest.csharp                 @microsoft.azure/autorest.modeler
 ---> Using cache
 ---> 1617776bc33e
Step 14/26 : RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
 ---> Using cache
 ---> 402db4094b4e
Step 15/26 : RUN mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
 ---> Using cache
 ---> 566248fed782
Step 16/26 : RUN curl https://packages.microsoft.com/config/debian/9/prod.list > prod.list
 ---> Using cache
 ---> 845076f45e3e
Step 17/26 : RUN mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
 ---> Using cache
 ---> 7e8808324ff9
Step 18/26 : RUN chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
 ---> Using cache
 ---> f1841a985bc4
Step 19/26 : RUN chown root:root /etc/apt/sources.list.d/microsoft-prod.list
 ---> Using cache
 ---> 0c8dda5527cb
Step 20/26 : RUN apt-get update
 ---> Using cache
 ---> e68bed6d6b4b
Step 21/26 : RUN apt-get install -yy -q dotnet-hosting-2.0.8
 ---> Using cache
 ---> 6291ba40751f
Step 22/26 : COPY swagger-codegen/generate_client_in_container.sh /generate_client.sh
 ---> Using cache
 ---> 09256aa48da8
Step 23/26 : COPY preprocess_spec.py /
 ---> Using cache
 ---> 293dc7183779
Step 24/26 : COPY custom_objects_spec.json /
 ---> Using cache
 ---> 37817bacd59e
Step 25/26 : COPY ${GENERATION_XML_FILE} /generation_params.xml
 ---> Using cache
 ---> 171c1dbd761b
Step 26/26 : ENTRYPOINT ["mvn-entrypoint.sh", "/generate_client.sh"]
 ---> Using cache
 ---> 0768743170bb
Successfully built 0768743170bb
Successfully tagged kubernetes-java-client-gen:v1
--- Running generator inside container...
/source/swagger-codegen /
/
--- Downloading and pre-processing OpenAPI spec
Traceback (most recent call last):
  File "//preprocess_spec.py", line 351, in <module>
    sys.exit(main())
  File "//preprocess_spec.py", line 339, in main
    with pool.request('GET', spec_url, preload_content=False) as response:
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 68, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 89, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 326, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 670, in urlopen
    **response_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /kubernetes/kubernetes/release-1.14/api/openapi-spec/swagger.json (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
```

When trying to generate API for `release-1.14`. This is the details of my OS:
```
$ uname -a
Darwin ip-10-10-26-39.ap-southeast-1.compute.internal 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin
```

**Comment by DarshanMurthy** [comment]
@irvifa I am stuck with this issues too..

**Comment by yue9944882** [comment]
i sent the change in the generator scripts #115. before this, i thought it's a regional issue. @irvifa can you verify if the change resolve the problem?

**Comment by irvifa** [comment]
@yue9944882 hmm still got the same error

**Comment by yue9944882** [comment]
/cc @roycaihw 

kindly ping for help from python gang

**Comment by irvifa** [comment]
This is the additional error I got:
```
After this operation, 197 MB of additional disk space will be used.
Get:1 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.0 amd64 2.0.0-1 [18.1 MB]
Get:2 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.3 amd64 2.0.3-1 [5804 kB]
Get:3 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.5 amd64 2.0.5-1 [1163 kB]
Get:4 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.6 amd64 2.0.6-1 [6865 kB]
Get:5 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.7 amd64 2.0.7-1 [13.8 kB]
Get:6 https://packages.microsoft.com/debian/9/prod stretch/main amd64 aspnetcore-store-2.0.8 amd64 2.0.8-1 [6194 kB]
Err:7 https://packages.microsoft.com/debian/9/prod stretch/main amd64 dotnet-host amd64 2.2.5-1
  404  Not Found
Get:8 https://packages.microsoft.com/debian/9/prod stretch/main amd64 dotnet-hostfxr-2.0.7 amd64 2.0.7-1 [135 kB]
Get:9 https://packages.microsoft.com/debian/9/prod stretch/main amd64 dotnet-runtime-2.0.7 amd64 2.0.7-1 [18.5 MB]
Get:10 https://packages.microsoft.com/debian/9/prod stretch/main amd64 dotnet-hosting-2.0.8 amd64 2.0.8-1 [2402 B]
Fetched 56.8 MB in 13s (4065 kB/s)
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/pool/main/d/dotnet-host/dotnet-host-2.2.5-x64.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -yy -q dotnet-hosting-2.0.8' returned a non-zero code: 100
```

seems like: `https://packages.microsoft.com/debian/9/prod/pool/main/d/dotnet-host/dotnet-host-2.2.5-x64.deb` doesn't exist anymore

**Comment by roycaihw** [comment]
I think it's from a change in [urllib3 1.25 (2019-04-22)](https://pypi.org/project/urllib3/): `Require and validate certificates by default when using HTTPS`. Before that we were just emitting `InsecureRequestWarning`

short term fix can be either [pinging](https://github.com/kubernetes-client/gen/blob/master/openapi/openapi-generator/Dockerfile#L21) `pip install urllib3==1.24.2` or using `CERT_NONE` / `CERT_OPTIONAL`

long term we may think about properly setting up cert
